CHANGES.rst
aplpy/core.py

I have seen slowdowns in the past due to the fact that the whole figure was re-drawn every time something was added to the figure. We only need to default to ``auto_refresh=True`` when using IPython and using an interactive Matplotlib backend.

Only set auto_refresh=True by default when using IPython with an interactive backend

---

aplpy/regions.py

I was getting this error message when I tried ```fig.show_regions(region_list)``` where ```region_list``` is a pyregion ShapeList or ```fig.show_regions('regions.reg')```.  I figured out a solution that works on my machine. 
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-372-c7aa93ef5953> in <module>()
----> 1 fig.show_regions(region_list)
/Users/alyo7318/anaconda/anaconda/lib/python2.7/site-packages/aplpy/regions.pyc in show_regions(self, region_file, layer, **kwargs)
/Users/alyo7318/anaconda/anaconda/lib/python2.7/site-packages/aplpy/decorators.pyc in _auto_refresh(f, *args, **kwargs)
23     mydata.nesting = getattr(mydata, 'nesting', 0) + 1
24     try:
---> …
```

Created astropy.wcs.wcs.WCS object out of self._header

---

.travis.yml
ah_bootstrap.py
aplpy/conftest.py

Miniconda's default prefix changed recently causing all travis builds failing.
And while I was at it I've updated the helpers to the latest one and opted in container based travis.
Also customised the testing header to contain the optional dependencies, and aplpy's version.

Fixing miniconda path in .travis.xml and updating helpers

---

aplpy/overlays.py

Doing the following:
```
F.scalebar.set_linewidth(5)
F.scalebar.set_length(100)
```
results in an error like:
```
File "/Users/adam/repos/aplpy/aplpy/overlays.py", line 245, in set_length
self._set_label_properties(**self._scalebar_settings)
File "<string>", line 2, in _set_label_properties
File "/Users/adam/repos/aplpy/aplpy/decorators.py", line 25, in _auto_refresh
return f(*args, **kwargs)
File "/Users/adam/repos/aplpy/aplpy/overlays.py", line 364, in _set_label_properties
self._scalebar.txt_label.get_children()[0].set(**kwargs)
File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/artist.py", line 827, in set
func = getattr(self, funcName)
AttributeError: 'Text' object has no attribute 'set_linewidth'
```

Scalebar bugfix

---

aplpy/tests/data/2d_fits/1904-66_HPX.hdr
aplpy/tests/test_colorbar.py
docs/quick_reference.rst

A few small changes to the name associated with Jy/beam and MJy/sr. Changed from flux or flux density to surface brightness. Originally brought up in this [issue](https://github.com/aplpy/aplpy/issues/296). Since I found a couple other spots where this was wrong compared to my original issue, I included fixing those as well.

Correct names for surface brightness units related to issue 296

---

aplpy/ticks.py

Matplotlib has deprecated get_axes() in favor of the axes property.
I haven't tested which versions of mpl support the axes property, but since this PR targets APLpy 2, I'd assume the matplotlib version dependency should be ok.
Fixes #294

Use axis.axes property instead of get_axes()

---

aplpy/core.py

Hi,
there is a trivial error in aplpy that is triggered when reading files with the list of HDUs. See exception below. The one liner fix is in the pull request. I guess this needs to be added to the list of tests. I think currently there is no test of FitsFigure with the proper HDUList in the file. I didn't have time to write the test though.
```
In [2]: get_dss.get_dss(180,30)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-16359f16ef2a> in <module>()
----> 1 get_dss.get_dss(180,30)
/home/koposov/astrolibpy/my_utils/get_dss.py in get_dss(ra, dec, survey, radius, debug, noerase, subplot)
30         if not noerase:
31                 plt.clf()
---> 32 …
```

fix the bug with HDUList

---

aplpy/regions.py

Since pyregion no longer accepts WCS objects, we have to pass it a Header object, which means doing the very unfortunate and hacky direct header keyword manipulation I had previously tried to avoid.  This is an unfortunate indirect consequence of the loss of `.naxis*` that has slowly reverberated throughout the astropy ecosystem...
See also:
https://github.com/astropy/astropy/issues/4669
https://github.com/aplpy/aplpy/pull/284
https://github.com/astropy/astropy/pull/5411

Fix issues with region parsing/plotting

---

aplpy/colorbar.py
aplpy/core.py
aplpy/overlays.py

Looks like `mpl_toolkits.axes_grid` is deprecated in new `matplotlib` versions, as importing `aplpy` triggers a deprecation warning (`mpl.__version__ = 2.0.2+4333.g1bf8282`):
```
The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
```
The second commit is needed because some functionality for `axes_grid`, like the `toggle_axislines` method, was [moved](https://github.com/matplotlib/matplotlib/commit/867d6f1fd05c1377feab5190e289ed6328307b81) to `axisartist`. I've rewired `axes_grid` through `axes_grid1` and `axisartist`, following the [exact same way](https://github.com/matplotlib/matplotlib/blob/b17e5d68e12c40c61bf972a084aa137d839a57d3/lib/mpl_toolkits/axes_grid/parasite_axes.py) …

Fix deprecation for axes_grid

---

.travis.yml

The qt version issue seems to be resolved, so this workaround can be removed now.

Removing workaround of qt version pinning

---

aplpy/labels.py

When the labels are displayed in LaTeX, the unit symbols for the right ascension coordinates (that is, the h, m, s, for hour, minute, and second, respectively) were shown in math mode, and thus in italic form.
To verify the standards of the International System of Units, the units h,m,s must be displayed in roman mode, and not in italic one.
This request fixes this behavior and now the unit symbols are displayed in roman mode.

coordinate labels in LaTeX now in roman

---

aplpy/ticks.py

Without break compatibility with previous versions, now the user can specify a different frequency for the minor ticks on each axis.
set_minor_frequency now accepts two arguments (the frequency for xaxis and for yaxis) instead of only one. If the second one is not supplied, then it produces the same behavior than previously (the same frequency for both axes).
This avoids ending with ticks that were only useful for one of the axis because they produced not standard intervals in the other axis.

Minor frequency

---

aplpy/core.py

This allows one to pass a rotation angle to show_rectangles. The rectangle are rotated around the center position.

Allow rotation of a rectangle around center

---

aplpy/core.py

when using a wcs object (as from an AVM file), must set .naxis1 and .naxis2,
not just .nx and .ny

AVM/WCS fix: set NAXIS

---

CHANGES.rst
aplpy/core.py

The change is a trivial update following 699edb9c9d98996b15f58fde5690030dc9fcb63c.
On my machine, the tests passed by
```
../../anaconda3/envs/aplpy_dev/lib/python3.6/site-packages/aplpy-0.0.dev1007-py3.6.egg/aplpy/tests/test_axis_labels.py ......
../../anaconda3/envs/aplpy_dev/lib/python3.6/site-packages/aplpy-0.0.dev1007-py3.6.egg/aplpy/tests/test_beam.py ............................
../../anaconda3/envs/aplpy_dev/lib/python3.6/site-packages/aplpy-0.0.dev1007-py3.6.egg/aplpy/tests/test_colorbar.py ........
../../anaconda3/envs/aplpy_dev/lib/python3.6/site-packages/aplpy-0.0.dev1007-py3.6.egg/aplpy/tests/test_contour.py ..
../../anaconda3/envs/aplpy_dev/lib/python3.6/site-packages/aplpy-0.0.dev1007-py3.6.egg/aplpy/tests/test_convolve.py .... …
```

Removes remaining image_util dependence [#364]

---

aplpy/regions.py

Apparently the "header" can be passed to show_regions as a WCS object.  This PR accommodates that use case

In show_regions, allow WCS "headers"

---

aplpy/decorators.py

This fixes compatibility with astropy 5.0.1, similar to https://github.com/astropy/pyvo/pull/283

Get wraps from functools instead of astropy

---

aplpy/tests/test_save.py

When updating from matplotlib 3.3.4 to matplotlib 3.4.1, I noticed the following errors in the test suite: https://gist.github.com/rmcgibbo/60f94457ca5852e96843feda27596910
This patch should fix test_save.py to be compatible with the new version of matplotlib as well as the old version. The change is that there's no more "comment" node in the SVG, so the offsets are shifted by 1 and what was previously childNode[2] is now childNode[1].

Updates test_save.py for matplotlib 3.4

---

aplpy/ticks.py

This is a fix for bugs 435 and 433.  A typo in the master branch code causes an exception when trying to set tick direction.

fix for bugs #435 and 433. Tick referenced ax instead of _ax

---

aplpy/axis_labels.py

During a code reorganization in Astropy 6.1, the jyear/byear attribute is no  longer a  class attribute in  astropy.coordinates.equinox, but  only an instance  attribute.
This makes a number of tests fail like
```Python
_____________________________ test_beam_add_remove _____________________________
def test_beam_add_remove():
>       f = FITSFigure(HDU)
[…]
>           equinox = "{:g}".format(FK5.equinox.jyear)
E           AttributeError: 'TimeAttribute' object has no attribute 'jyear'
/usr/lib/python3/dist-packages/aplpy/axis_labels.py:47: AttributeError
```
As discussed in https://github.com/astropy/astropy/issues/16654, the best way to fix it is here. Aside of adopting the (onforeseen) API change, it may  be  useful to  take the  possibily modified equinox time hear instead of the …

Use FK4/FK5 instances instead of classes to get the equinox year

---

aplpy/core.py

The `matplotlib.cm.get_cmap` API was deprecated in 3.7, and removed in 3.9, but `matplotlib.pyplot.get_cmap` remains available.

Fix cmap handling with Matplotlib 3.9

---

aplpy/overlays.py

Trying to get the figure tests passing again...

Fixed use of AnchoredEllipse, removed in recent Matplotlib versions
